import { SignInButton, SignOutButton, useUser,UserButton } from "@clerk/nextjs";
import { User } from "@clerk/nextjs/dist/types/server";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const user = useUser();
  if(!user.isSignedIn) return null;
  return (
    <UserButton />
  );
}



const Home: NextPage = () => {
  const user = useUser();

  const{data, isLoading} = api.posts.getAll.useQuery();

  if(isLoading) return (<div>Loading...</div>);

  if(!data) return (<div>Something went wrong</div>);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full md:max-w-2xl border-slate-400 border-x ">
        <div className="border-b border-slate-400 p-4">
          {!user.isSignedIn&&<div className="flex justify-center"><SignInButton /></div>}
          {!!user.isSignedIn&&<CreatePostWizard />}
        </div>
        <div className="flex flex-col">
          {[...data, ...data]?.map((post) => (<div key={post.id} className="border-b border-slate-400 p-8">
            {post.content  }
            </div>
          ))}
        </div>
        </div>
      </main>
    </> 
  );
};

export default Home;
